# Generated by Django 5.1.3 on 2026-05-11 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pigeons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sortie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_sortie",
                    models.CharField(
                        choices=[
                            ("vente", "Vente"),
                            ("deces", "Décès"),
                            ("perte", "Perte"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_sortie", models.DateField()),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("acheteur", models.CharField(blank=True, max_length=200, null=True)),
                ("cause", models.TextField(blank=True, null=True)),
                ("circonstances", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pigeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorties",
                        to="pigeons.pigeon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sortie",
                "verbose_name_plural": "Sorties",
                "ordering": ["-date_sortie"],
            },
        ),
    ]
