# Generated by Django 5.1.3 on 2026-05-11 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("couples", "__first__"),
        ("pigeons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Numéro de cage"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="Superficie (m²)",
                    ),
                ),
                (
                    "position_x",
                    models.IntegerField(default=0, verbose_name="Position X (grille)"),
                ),
                (
                    "position_y",
                    models.IntegerField(default=0, verbose_name="Position Y (grille)"),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Cage active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cage",
                "verbose_name_plural": "Cages",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_occupation",
                    models.CharField(
                        choices=[("seul", "Pigeon seul"), ("couple", "Couple")],
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "cage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupations",
                        to="cages.cage",
                    ),
                ),
                (
                    "couple",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="couples.couple",
                    ),
                ),
                (
                    "pigeon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pigeons.pigeon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occupation",
                "verbose_name_plural": "Occupations",
                "ordering": ["-date_debut"],
            },
        ),
    ]
