# Generated by Django 5.1.3 on 2026-05-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueCage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("occupation", "Occupation"),
                            ("liberation", "Libération"),
                            ("nettoyage", "Nettoyage"),
                            ("creation", "Création"),
                            ("modification", "Modification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "cage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="cages.cage",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_action"],
            },
        ),
    ]
