# Generated by Django 5.1.3 on 2026-05-11 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pigeons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Couple",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_formation", models.DateField(auto_now_add=True)),
                ("date_rupture", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("rompu", "Rompu")],
                        default="actif",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "femelle",
                    models.ForeignKey(
                        limit_choices_to={"sexe": "F", "statut": "actif"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="couples_femelle",
                        to="pigeons.pigeon",
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        limit_choices_to={"sexe": "M", "statut": "actif"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="couples_male",
                        to="pigeons.pigeon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Couple",
                "verbose_name_plural": "Couples",
                "unique_together": {("male", "femelle", "statut")},
            },
        ),
    ]
