# Generated by Django 5.1.3 on 2026-05-12 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColombierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        default="Mon Colombier",
                        max_length=200,
                        verbose_name="Nom du colombier",
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Senegal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ville / Région"
                    ),
                ),
                (
                    "gps",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Coordonnées GPS",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proprietaire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colombier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du colombier",
                "verbose_name_plural": "Configurations des colombiers",
                "db_table": "colombier_config",
            },
        ),
    ]
