# Generated by Django 5.1.3 on 2026-05-11 02:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("couples", "0001_initial"),
        ("pigeons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reproduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_ponte", models.DateField(verbose_name="Date de ponte")),
                ("date_eclosion", models.DateField(verbose_name="Date d'éclosion")),
                (
                    "nombre_oeufs",
                    models.IntegerField(default=2, verbose_name="Nombre d'oeufs"),
                ),
                (
                    "nombre_jeunes",
                    models.IntegerField(default=0, verbose_name="Nombre de jeunes nés"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reproductions",
                        to="couples.couple",
                    ),
                ),
                (
                    "jeunes",
                    models.ManyToManyField(
                        blank=True, related_name="naissances", to="pigeons.pigeon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reproduction",
                "verbose_name_plural": "Reproductions",
                "ordering": ["-date_ponte"],
            },
        ),
    ]
