# Generated by Django 5.1.3 on 2026-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pigeons", "0003_pigeon_generation_pigeon_origine_and_more"),
        ("reproductions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reproduction",
            name="date_sevrage",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de sevrage"
            ),
        ),
        migrations.AddField(
            model_name="reproduction",
            name="nombre_eclos",
            field=models.IntegerField(default=0, verbose_name="Nombre d'éclos"),
        ),
        migrations.AddField(
            model_name="reproduction",
            name="statut",
            field=models.CharField(
                choices=[
                    ("incubation", "Incubation"),
                    ("eclosion", "Éclosion"),
                    ("sevrage", "Sevrage"),
                    ("termine", "Terminé"),
                ],
                default="incubation",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="reproduction",
            name="date_eclosion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'éclosion"
            ),
        ),
        migrations.AlterField(
            model_name="reproduction",
            name="jeunes",
            field=models.ManyToManyField(
                blank=True,
                related_name="naissances",
                to="pigeons.pigeon",
                verbose_name="Pigeonneaux bagués",
            ),
        ),
    ]
