# Generated by Django 5.1.3 on 2026-05-11 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pigeon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Matricule (bague)"
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Mâle"), ("F", "Femelle")],
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                ("race", models.CharField(max_length=100, verbose_name="Race")),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                (
                    "couleur",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Couleur"
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Poids (g)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("vendu", "Vendu"),
                            ("mort", "Mort"),
                            ("perdu", "Perdu"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants_mere",
                        to="pigeons.pigeon",
                        verbose_name="Mère",
                    ),
                ),
                (
                    "pere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants_pere",
                        to="pigeons.pigeon",
                        verbose_name="Père",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pigeon",
                "verbose_name_plural": "Pigeons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["matricule"], name="pigeons_pig_matricu_512c90_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="pigeons_pig_statut_e1f21b_idx"
                    ),
                    models.Index(fields=["sexe"], name="pigeons_pig_sexe_c84ab9_idx"),
                ],
            },
        ),
    ]
