# Generated by Django 5.1.3 on 2026-05-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pigeons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PigeonEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("medical", "Médical"),
                            ("vaccination", "Vaccination"),
                            ("reproduction", "Reproduction"),
                            ("concours", "Concours"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pigeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="pigeons.pigeon",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
