# Generated by Django 5.1.3 on 2026-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pigeons", "0002_pigeonevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="pigeon",
            name="generation",
            field=models.PositiveIntegerField(default=0, verbose_name="Génération"),
        ),
        migrations.AddField(
            model_name="pigeon",
            name="origine",
            field=models.CharField(
                choices=[
                    ("ne", "Né dans le colombier"),
                    ("achete", "Acheté"),
                    ("don", "Don"),
                    ("echange", "Échange"),
                ],
                default="ne",
                max_length=20,
                verbose_name="Origine",
            ),
        ),
        migrations.AddIndex(
            model_name="pigeon",
            index=models.Index(
                fields=["generation"], name="pigeons_pig_generat_a4111f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pigeon",
            index=models.Index(fields=["pere"], name="pigeons_pig_pere_id_de72de_idx"),
        ),
        migrations.AddIndex(
            model_name="pigeon",
            index=models.Index(fields=["mere"], name="pigeons_pig_mere_id_37da38_idx"),
        ),
    ]
